### ISSUE TITLE
Skeet not recognizing command for namespace

### ISSUE THREAD

**Issue by paulsybrandy** [knowsuchagency/broski#4]
So I almost have everything complete except for making sure skeet knows the default namespace. 

1. I have created the file as per documentation and placed it in the same directory as the config.yml file. 
2. I then run the following command: `skeet -n namespace.yml`

The output  skeet gives me is the options I can run skeet with:

> Usage: skeet [OPTIONS] [QUERY]...
> 
>   Describe what you want done, and Skeet will use AI to make it happen.
> 
> Options:
>   -y, --yolo            Automatically execute scripts and commands without
>                         asking for confirmation.
>   -m, --model TEXT      Specify the LLM model to use
>   -k, --api-key TEXT    API key for the LLM service
>   -a, --attempts TEXT   Maximum number of script execution attempts. If less
>                         than 0, the program will loop until the script is
>                         successful, regardless of errors.
>   -e, --verify          If true, the llm will verify the query was satisfied.
>                         By default, the program will terminate if the script
>                         or command returns a zero exit code.
>   -x, --cleanup         If true, the program will clean up the temporary file
>                         after running the script.
>   -U, --upgrade         Upgrade Skeet to the latest version with uv.
>   -n, --namespace TEXT  Specify the configuration namespace to use for the LLM
>                         model.
>   -v, --verbose         If true, the program will print verbose output.
>   -s, --synchronous     If true, the program will NOT stream the output of the
>                         script -- it will run synchronously. This is the
>                         default behavior EXCEPT when using python.
>   -p, --python          If true, the program will use Python to satisfy your
>                         query.
>   --version             Show the version and exit.
>   --help                Show this message and exit.

3. I try running the same command with the full path of the namespace.yml file: `skeet -n C:\Users\pauln\.config\skeet\namespace.yml`

The same result occurs. 

I am at a loss. According to the documentation, and the commands skeet spits out to me every time, I am using the command correctly so why is it not seeming to comprehend the command? Please help. This is the last step in finally getting it to work. Thanks in advance.

**Comment by knowsuchagency** [comment]
The argument to `--namespace` isn't the path to the file, it's the namespace you want to use. It's always going to read from `~/.config/skeet/config.yaml` or in your case, `C:\Users\pauln\.config\skeet\config.yaml`.  

https://github.com/knowsuchagency/skeet?tab=readme-ov-file#configuration

If you have a configuration file like the one in the docs, valid arguments would be default, openai, anthropic, google, or ollama.

**Comment by paulsybrandy** [comment]
So @knowsuchagency, that would mean, if I am reading it correctly, the only thing I need to change in my config.yaml file is the top line? Sorry but I want to make sure I finally understand and do it correctly. I am not at all familiar with this format.

My current config.yaml:

```
default: namespace.yaml
  model: "ollama_chat/phi3:medium" # Default LLM model to use
  api_key: [REMOVED] # Your LLM API key
  yolo: false # Automatically execute scripts and commands without asking for confirmation
  attempts: 5 # Maximum number of execution attempts
  verify: false # Whether to verify output with LLM
  cleanup: false # Whether to clean up temporary files
  synchronous: false # Whether to run in synchronous mode
  python: false # Whether to use Python scripts instead of shell commands
  litellm_kwargs: # Extra arguments to pass to LiteLLM

openai: # OpenAI-specific configuration
  model: "o1-mini"
  api_key: [REMOVED]

anthropic: # Anthropic-specific configuration
  model: "claude-3-5-sonnet-20240620"
  api_key: [REMOVED]

google: # Google-specific configuration
  model: "google/gemini-2.0-flash-thinking-exp"
  api_key: [REMOVED]

ollama: # Local Ollama configuration
  model: "ollama_chat/phi3:medium"
  api_key: [REMOVED]
```

and change basically the first line to:

```
default: 
  model: "ollama_chat/phi3:medium" # Default LLM model to use
  api_key: [REMOVED] # Your LLM API key
  yolo: false # Automatically execute scripts and commands without asking for confirmation
  attempts: 5 # Maximum number of execution attempts
  verify: false # Whether to verify output with LLM
  cleanup: false # Whether to clean up temporary files
  synchronous: false # Whether to run in synchronous mode
  python: false # Whether to use Python scripts instead of shell commands
  litellm_kwargs: # Extra arguments to pass to LiteLLM

openai: # OpenAI-specific configuration
  model: "o1-mini"
  api_key: [REMOVED]

anthropic: # Anthropic-specific configuration
  model: "claude-3-5-sonnet-20240620"
  api_key: [REMOVED]

google: # Google-specific configuration
  model: "google/gemini-2.0-flash-thinking-exp"
  api_key: [REMOVED]

ollama: # Local Ollama configuration
  model: "ollama_chat/phi3:medium"
  api_key: [REMOVED]
```
